Repository jody/helloCS3250, pull requests merged in 2020-10, with the labels that each got.

#4 Fix for Checkstyle error in HelloWorld.java (Issue #2)
  src/metrocs/HelloWorld.java
Labels: convention violation

#7 Improve README
  README.md
Labels: documentation

#9 Checkstyle error fix - HelloWorldTest.java #5
  src/metrocs/HelloWorldTest.java
Labels: convention violation

#26 I fixed the Junit error
  src/metrocs/HelloWorld.java
Labels: bug

#28 Fix for sayHelloEmptyStringTest(). (Issue #13)
  src/metrocs/HelloWorld.java
Labels: bug
